# Generated by Django 5.2.17 on 2026-09-22 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("supabase_user_id", models.UUIDField(unique=True)),
                ("user_number", models.PositiveBigIntegerField(unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["username"], name="api_account_usernam_771f55_idx"
                    ),
                    models.Index(
                        fields=["user_number"], name="api_account_user_nu_a22133_idx"
                    ),
                ],
            },
        ),
    ]
