# Generated by Django 5.2.17 on 2026-09-22 17:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(
                max_length=30, unique=True, validators=[api.models.validate_username]
            ),
        ),
    ]
